COLORS = {
    PRIMARY_COLOR : '#EE4617',
    HEADER_TEXT_COLOR: '#fff',
    TAB_HEADER_BACKGROUND: '#fff',
    TEXT_BLACK: '#333',
    MAIN_BACKGROUND_COLOR: '#F9FAFF',
    POSITIVE_COLOR: '#4CCBFE',
    WHITE : '#fff',
    ORANGE_YELLOW: '#FFC86B',
    LIGHT_BLUE: '#00A4E0',
    DARK_GREEN:'#0098A3',
}

module.exports = COLORS;